version: "3.3"

services:
  proxy2:
    container_name: proxy2
    build:
      context: .
      dockerfile: ./proxy/Dockerfile
    restart: on-failure
    ports:
      - "1337:80"
    volumes:
      - "./proxy/sites-available.conf:/etc/nginx/sites-available/default.conf"
      - "./proxy/nginx.conf:/etc/nginx/nginx.conf"
  
  server1:
    container_name: server1
    build:
      context: .
      dockerfile: ./server1/Dockerfile
    depends_on:
      - mysql
      - proxy2
    restart: on-failure
    ports:
      - "2525:5000"
    expose:
      - "5000"

  server2:
    container_name: server2
    build:
      context: .
      dockerfile: ./server2/Dockerfile
    depends_on:
      - mysql
      - proxy2
    restart: on-failure
    ports:
      - "9453:3001"
    expose:
      - "3001"
    volumes:
      - "./server2/nginx.conf:/etc/nginx/sites-available/default.conf"

  mysql:
    image: mysql:5.7
    container_name: mysql
    restart: always
    volumes:
      - "./mysql/schema:/docker-entrypoint-initdb.d"
    environment:
      - MYSQL_ROOT_PASSWORD=local
      - MYSQL_DATABASE=ifb102
      - MYSQL_ALLOW_EMPTY_PASSWORD=no
    expose:
      - "3306"